// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

#pragma once

#include "AudioApi.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAudioApi final : ::djinni::JniInterface<::textsort::AudioApi, NativeAudioApi> {
public:
    using CppType = std::shared_ptr<::textsort::AudioApi>;
    using CppOptType = std::shared_ptr<::textsort::AudioApi>;
    using JniType = jobject;

    using Boxed = NativeAudioApi;

    ~NativeAudioApi();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeAudioApi>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeAudioApi>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeAudioApi();
    friend ::djinni::JniClass<NativeAudioApi>;
    friend ::djinni::JniInterface<::textsort::AudioApi, NativeAudioApi>;

};

}  // namespace djinni_generated
