// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

#import <Foundation/Foundation.h>


/**interface */
@interface TXSAudioApi : NSObject

+ (int64_t)createAudioApi;

- (int32_t)startAudiorecord:(int32_t)audioSource
             sampleRateInHz:(int32_t)sampleRateInHz
              channelConfig:(int32_t)channelConfig
                audioFormat:(int32_t)audioFormat
          bufferSizeInBytes:(int32_t)bufferSizeInBytes;

- (int32_t)stopAudiorecord;

@end
